=== robbyn/jedo/src/main/resources/org/tastefuljava/jedo/mapping/jedo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT mapping (class*)>
<!ATTLIST mapping package CDATA #IMPLIED>

<!ELEMENT class (id?,(property|component|reference|collection)*,
        load?,query*,insert?,update?,delete?,statement*)>
<!ATTLIST class name CDATA #REQUIRED>

<!ELEMENT id (property+)>

<!ELEMENT property EMPTY>
<!ATTLIST property
    name CDATA #REQUIRED
    column CDATA #IMPLIED
>

<!ELEMENT component (property+)>
<!ATTLIST component name CDATA #REQUIRED>

<!ELEMENT reference EMPTY>
<!ATTLIST reference
    name CDATA #REQUIRED
    column CDATA #REQUIRED
    fetch-mode (eager|lazy) #IMPLIED
>

<!ELEMENT collection (fetch|clear|add|remove)*>
<!ATTLIST collection
    name CDATA #REQUIRED
    query CDATA #IMPLIED
    fetch-mode (eager|lazy) #IMPLIED
>

<!ELEMENT load (#PCDATA)>

<!ELEMENT query (#PCDATA)>
<!ATTLIST query
    name CDATA #REQUIRED
    parameters CDATA #IMPLIED
>

<!ELEMENT insert (#PCDATA)>
<!ATTLIST insert get-generated-keys (true|false) #IMPLIED>

<!ELEMENT update (#PCDATA)>

<!ELEMENT delete (#PCDATA)>

<!ELEMENT statement (#PCDATA)>
<!ATTLIST statement
    name CDATA #REQUIRED
    parameters CDATA #IMPLIED
>

<!-- Collection queries -->

<!ELEMENT fetch (#PCDATA)>
<!ATTLIST fetch
    parent CDATA "parent"
>
<!ELEMENT clear (#PCDATA)>
<!ATTLIST clear
    parent CDATA "parent"
>
<!ELEMENT add (#PCDATA)>
<!ATTLIST add
    parent CDATA "parent"
    element CDATA "element"
>
<!ELEMENT remove (#PCDATA)>
<!ATTLIST remove
    parent CDATA "parent"
    element CDATA "element"
>

=== robbyn/jedo/src/test/resources/org/tastefuljava/jedo/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC '-//tastefuljava.org//Jedo Mapping File 1.0//EN' 'jedo.dtd'>
<mapping package="org.tastefuljava.jedo.testdb">
    <class name="Folder">
        <id>
            <property name="id" column="ID"/>
        </id>
        <reference name="parent" column="PARENT_ID" fetch-mode="lazy"/>
        <property name="name" column="NAME"/>
        <collection name="subfolders" fetch-mode="lazy">
            <fetch>
                SELECT * FROM folders
                WHERE PARENT_ID=${parent.id}
            </fetch>
        </collection>
        <collection name="pictures" fetch-mode="eager">
            <fetch parent="folder">
                SELECT * FROM pictures
                WHERE FOLDER_ID=${folder.id}
            </fetch>
            <add parent="folder" element="picture">
                UPDATE pictures
                SET FOLDER_ID=${folder.id}
                WHERE ID=${picture.id}
            </add>
            <remove parent="folder" element="picture">
                DELETE FROM pictures
                WHERE FOLDER_ID=${folder.id} AND ID=${picture.id}
            </remove>
            <clear parent="folder">
                DELETE FROM pictures
                WHERE FOLDER_ID=${folder.id}
            </clear>
        </collection>

        <load>
            SELECT * FROM folders
            WHERE ID=${id}
        </load>
        <query name="rootFolder" parameters="name">
            SELECT * FROM folders
            WHERE PARENT_ID IS NULL
                AND NAME=${name}
        </query>
        <query name="subfolder" parameters="parent,name">
            SELECT * FROM folders
            WHERE PARENT_ID=${parent.id}
                AND NAME=${name}
        </query>
    </class>

    <class name="Picture">
        <id>
            <property name="id" column="ID"/>
        </id>
        <reference name="folder" column="FOLDER_ID"/>
        <property name="name" column="NAME"/>
        <property name="timestamp" column="TIMESTAMP"/>
        <property name="width" column="WIDTH"/>
        <property name="height" column="HEIGHT"/>
        <component name="gpsData">
            <property name="latitude" column="LATITUDE"/>
            <property name="longitude" column="LONGITUDE"/>
            <property name="altitude" column="ALTITUDE"/>
        </component>

        <load>
            SELECT * FROM pictures
            WHERE ID=${id}
        </load>
        <query name="byName" parameters="folder,name">
            SELECT * FROM pictures
            WHERE FOLDER_ID=${folder.id}
                AND NAME=${name}
        </query>
        <insert get-generated-keys="true">
            INSERT INTO pictures(FOLDER_ID,NAME,TIMESTAMP,WIDTH,HEIGHT,LATITUDE,
                LONGITUDE,ALTITUDE)
            VALUES(${folder.id},${name},${timestamp:TIMESTAMP},${width},
                ${height},${gpsData.latitude},${gpsData.longitude},
                ${gpsData.altitude})
        </insert>
        <update>
            UPDATE pictures SET FOLDER_ID=${folder.id},NAME=${name},
                TIMESTAMP=${timestamp:TIMESTAMP},WIDTH=${width},
                HEIGHT=${height},LATITUDE=${gpsData.latitude},
                LONGITUDE=${gpsData.longitude},
                ALTITUDE=${gpsData.altitude}
            WHERE ID=${id}
        </update>
        <delete>
            DELETE FROM pictures WHERE ID=${id}
        </delete>
    </class>
</mapping>
