=== robbyn/jedo/example/jedo.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT mapping (class*)>
<!ATTLIST mapping package CDATA #IMPLIED>

<!ELEMENT class (id*,property*,load?,query*,insert?,update?,delete?)>
<!ATTLIST class name CDATA #REQUIRED>

<!ELEMENT id EMPTY>
<!ATTLIST id
    name CDATA #REQUIRED
    column CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
    name CDATA #REQUIRED
    column CDATA #IMPLIED
>

<!ELEMENT load (#PCDATA)>

<!ELEMENT query (#PCDATA)>
<!ATTLIST query
    name CDATA #REQUIRED
    parameters CDATA #IMPLIED
>

<!ELEMENT insert (#PCDATA)>
<!ATTLIST insert get-generated-keys (true|false) #IMPLIED>

<!ELEMENT update (#PCDATA)>

<!ELEMENT delete (#PCDATA)>

=== robbyn/jedo/test/org/tastefuljava/jedo/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC '-//tastefuljava.org//Jedo Mapping File 1.0//EN' 'jedo.dtd'>
<mapping package="org.tastefuljava.jedo.testdb">
    <class name="Folder">
        <id>
            <property name="id" column="ID"/>
        </id>
        <property name="parentId" column="PARENT_ID"/>
        <property name="name" column="NAME"/>

        <load>
            SELECT * FROM folders
            WHERE ID=${id}
        </load>
        <query name="rootFolder" parameters="name">
            SELECT * FROM folders
            WHERE PARENT_ID IS NULL
                AND NAME=${name}
        </query>
        <query name="subfolder" parameters="parent,name">
            SELECT * FROM folders
            WHERE PARENT_ID=${parent.id}
                AND NAME=${name}
        </query>
        <query name="subfolders" parameters="parent">
            SELECT * FROM folders
            WHERE PARENT_ID=${parent.id}
        </query>
    </class>

    <class name="Picture">
        <id>
            <property name="id" column="ID"/>
        </id>
        <property name="folderId" column="FOLDER_ID"/>
        <property name="name" column="NAME"/>
        <property name="timestamp" column="TIMESTAMP"/>
        <property name="width" column="WIDTH"/>
        <property name="height" column="HEIGHT"/>
        <component name="gpsData">
            <property name="latitude" column="LATITUDE"/>
            <property name="longitude" column="LONGITUDE"/>
            <property name="altitude" column="ALTITUDE"/>
        </component>

        <load>
            SELECT * FROM pictures
            WHERE ID=${id}
        </load>
        <query name="byName" parameters="folder,name">
            SELECT * FROM pictures
            WHERE PARENT_ID=${folder.id}
                AND NAME=${name}
        </query>
        <query name="inFolder" parameters="folder">
            SELECT * FROM pictures
            WHERE PARENT_ID=${folder.id}
        </query>
        <insert get-generated-keys="true">
            INSERT INTO pictures(FOLDER_ID,NAME,TIMESTAMP,WIDTH,HEIGHT,LATITUDE,
                LONGITUDE,ALTITUDE)
            VALUES(${folderId},${name},${timestamp},${width},${height},
                ${gpsData.latitude},${gpsData.longitude},${gpsData.altitude})
        </insert>
        <update>
            UPDATE pictures SET FOLDER_ID=${folderId},NAME=${name},
                TIMESTAMP=${timestamp},WIDTH=${width},HEIGHT=${height},
                LATITUDE=${gpsData.latitude},LONGITUDE=${gpsData.longitude},
                ALTITUDE=${gpsData.altitude}
            WHERE ID=${id}
        </update>
        <delete>
            DELETE FROM pictures WHERE ID=${id}
        </delete>
    </class>
</mapping>

=== robbyn/jedo/test/org/tastefuljava/jedo/mapping/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC '-//tastefuljava.org//Jedo Mapping File 1.0//EN' 'jedo.dtd'>
<mapping package="org.tastefuljava.jedo.testdb">
    <class name="Folder">
        <id>
            <property name="id" column="ID"/>
        </id>
        <property name="name" column="NAME"/>

        <load>
            SELECT * FROM folders
            WHERE ID=${id}
        </load>
        <query name="rootFolder" parameters="name">
            SELECT * FROM folders
            WHERE PARENT_ID IS NULL
                AND NAME=${name}
        </query>
        <query name="subfolder" parameters="parent,name">
            SELECT * FROM folders
            WHERE PARENT_ID=${parent.id}
                AND NAME=${name}
        </query>
        <query name="subfolders" parameters="parent">
            SELECT * FROM folders
            WHERE PARENT_ID=${parent.id}
        </query>
    </class>
</mapping>

=== robbyn/jedo/test/org/tastfuljava/jedo/mapping/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC '-//tastefuljava.org//Jedo Mapping File 1.0//EN' 'jedo.dtd'>
<mapping package="org.tastefuljava.gianadda.domain">
    <class name="Folder">
        <id>
            <property name="id" column="ID"/>
        </id>
        <property name="name" column="NAME"/>

        <load>
            SELECT * FROM folders
            WHERE ID=${id}
        </load>
        <query name="rootFolder" parameters="name">
            SELECT * FROM folders
            WHERE PARENT_ID IS NULL
                AND NAME=${name}
        </query>
        <query name="subfolder" parameters="parentId,name">
            SELECT * FROM folders
            WHERE PARENT_ID=${parentId}
                AND NAME=${name}
        </query>
        <query name="subfolders" parameters="parentId">
            SELECT * FROM folders
            WHERE PARENT_ID=${parentId}
        </query>
    </class>
</mapping>
